name: Check PR

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  buildDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and setup Java
        uses: ./.github/workflows/checkoutAndSetup.yml

      - name: Build Debug
        run: ./gradlew assembleDebug

  testDebug:
    runs-on: ubuntu-latest
    needs: buildDebug

    steps:
      - name: Checkout and setup Java
        uses: ./.github/workflows/checkoutAndSetup.yml

      - name: Run debug unit tests
        run: ./gradlew testDebug

  buildRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and setup Java
        uses: ./.github/workflows/checkoutAndSetup.yml

      - name: Build Release
        run: ./gradlew assembleRelease

  testRelease:
    runs-on: ubuntu-latest
    needs: buildRelease

    steps:
      - name: Checkout and setup Java
        uses: ./.github/workflows/checkoutAndSetup.yml

      - name: Run release unit tests
        run: ./gradlew testRelease