name: Check PR

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  buildDebug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build Debug
        run: ./gradlew assembleDebug

  testDebug:
    runs-on: ubuntu-latest
    needs: buildDebug

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run debug unit tests
        run: ./gradlew testDebug

  buildRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build Release
        run: ./gradlew assembleRelease

  testRelease:
    runs-on: ubuntu-latest
    needs: buildRelease

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run release unit tests
        run: ./gradlew testRelease