name: Check PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  assembleDebug:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Assemble Debug
        run: ./gradlew assembleDebug --stacktrace

  assembleRelease:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Assemble Release
        run: ./gradlew assembleRelease --stacktrace

  check:
    runs-on: macos-latest
    needs: [assembleDebug, assembleRelease]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run checks
        run: ./gradlew check --stacktrace

  detekt:
    runs-on: macos-latest
    needs: [ assembleDebug, assembleRelease ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run detekt
        run: ./gradlew detektAll